### ISSUE TITLE
DELETE'd case reports still visible in Explore

### ISSUE THREAD

**Issue by southalln** [tsheils/project_cure_issues#71]
Case report was submitted, and then deleted by user from Profile page. Nevertheless, search on Leish, 
https://dev.emochacure.com/view-case?diseaseId=285&diseaseName=Leishmaniasis
and this case still shows up (Note there are multiple cases with this drug -- report ID: 3465 is for a deleted case, however):

Disulfiram

    Regimen: Disulfiram, Paracetamol

    Author: southalln@mail.nih.gov (posted anonymously) | Created: 2017-04-27 | Country: Not Specified | Outcome: Patient was cured | Report ID: 3465

**Comment by emochaadmin** [comment]
Same as #25 ?

**Comment by tsheils** [comment]
@emochaadmin , this one is slightly different, #25 was an actual deletion from the database, which we shouldn't really need to do, it was done in the django admin panel. This issue is for a user submitted deletion, meaning the status should change from "Submitted" or "approved" to deleted. It is likely that there are no checks in place, in order to test the data (submitted vs improved).
